In [1]:
import tensorflow as tf

In [4]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

vector = tf.constant([1.,2.,3.])
scalar = tf.constant(1.)
matrix = tf.constant([[1.,2.],[3.,4.]])
tensor = tf.constant([[[1,2,3,],
                       [4,5,6,]],
                      [[7,8,9],
                       [10,11,12]]
                     ])
vector,scalar,matrix,tensor

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [9]:
# 2. Find the shape, rank and size of the tensors you created in 1.

vector.shape, tf.rank(vector), tf.size(vector)

(TensorShape([3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [10]:
scalar.shape, tf.rank(scalar), tf.size(scalar)

(TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [11]:
matrix.shape, tf.rank(matrix), tf.size(matrix)

(TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [12]:
tensor.shape, tf.rank(tensor), tf.size(tensor)

(TensorShape([2, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [18]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300]

tensor1 = tf.random.Generator.from_seed(0)
tensor1 = tensor1.uniform(shape = (5,300))
tensor2 = tf.random.Generator.from_seed(40)
tensor2 = tensor2.uniform(shape = (5,300))

tensor1,tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.31179297, 0.8263413 , 0.6849456 , ..., 0.56451845, 0.44649565,
         0.41026497],
        [0.60833323, 0.50973356, 0.31043375, ..., 0.50437474, 0.6110033 ,
         0.7943536 ],
        [0.20573044, 0.5442884 , 0.10470831, ..., 0.18146193, 0.26921892,
         0.71201587],
        [0.31422472, 0.15571809, 0.59350574, ..., 0.21489167, 0.96785796,
         0.13088453],
        [0.00473952, 0.06306279, 0.91214204, ..., 0.7092078 , 0.93488145,
         0.7450988 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6332247 , 0.15466881, 0.6757076 , ..., 0.4899974 , 0.9779571 ,
         0.29513252],
        [0.9572704 , 0.5485532 , 0.27353418, ..., 0.2999829 , 0.59305775,
         0.5654199 ],
        [0.16357625, 0.5648166 , 0.9018372 , ..., 0.50409853, 0.4650793 ,
         0.8246126 ],
        [0.61024106, 0.7240714 , 0.5206388 , ..., 0.15108037, 0.60569584,
         0.93234086],
        [0.10864

In [19]:
tf.reduce_max(tensor1), tf.reduce_min(tensor1), tf.reduce_max(tensor2), tf.reduce_min(tensor2)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99883735>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0003619194>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99872065>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0003619194>)

In [20]:
tensor1 == tensor2

<tf.Tensor: shape=(5, 300), dtype=bool, numpy=
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])>

In [21]:
#4.  Multiply the two tensors you created in 3 using matrix multiplication.

tf.matmul(tensor1, tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.476265, 73.7752  , 70.76349 , 73.16104 , 76.47807 ],
       [81.03289 , 73.43579 , 77.032486, 78.511116, 78.1142  ],
       [74.80905 , 71.91706 , 72.52008 , 73.16179 , 73.73898 ],
       [71.914215, 67.78902 , 70.45873 , 69.44948 , 69.19539 ],
       [75.09321 , 70.84514 , 72.7342  , 73.69817 , 74.27143 ]],
      dtype=float32)>

In [23]:
# 5. Multiply the two tensors you created in 3 using dot product.

tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.476265, 73.7752  , 70.76349 , 73.16104 , 76.47807 ],
       [81.03289 , 73.43579 , 77.032486, 78.511116, 78.1142  ],
       [74.80905 , 71.91706 , 72.52008 , 73.16179 , 73.73898 ],
       [71.914215, 67.78902 , 70.45873 , 69.44948 , 69.19539 ],
       [75.09321 , 70.84514 , 72.7342  , 73.69817 , 74.27143 ]],
      dtype=float32)>

In [26]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

tensor = tf.random.Generator.from_seed(0)
tensor = tensor.uniform(shape = (224,224,3))
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.31179297, 0.8263413 , 0.6849456 ],
        [0.0067091 , 0.78749514, 0.3906511 ],
        [0.29263055, 0.99216926, 0.95810425],
        ...,
        [0.43970728, 0.976676  , 0.8946736 ],
        [0.9747398 , 0.7011992 , 0.73613393],
        [0.4360633 , 0.7536833 , 0.01353109]],

       [[0.2823602 , 0.0927937 , 0.2424469 ],
        [0.92214036, 0.1318667 , 0.18895125],
        [0.13469017, 0.29916108, 0.22880554],
        ...,
        [0.10263181, 0.3771491 , 0.7380618 ],
        [0.6484846 , 0.69211054, 0.67284966],
        [0.43589175, 0.48166   , 0.14082742]],

       [[0.41235518, 0.45162737, 0.6804353 ],
        [0.04887676, 0.6775023 , 0.29143417],
        [0.3466624 , 0.17450547, 0.38451958],
        ...,
        [0.8667455 , 0.16113937, 0.67500424],
        [0.8560462 , 0.48929954, 0.97561824],
        [0.5725883 , 0.8036673 , 0.3923154 ]],

       ...,

       [[0.68855166, 0.3706571 , 0.03126299],
        [0.61

In [29]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.

tf.reduce_min(tensor, axis = 0), tf.reduce_max(tensor, axis = 0)

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[3.21269035e-03, 5.00202179e-04, 2.84492970e-03],
        [8.69870186e-04, 1.46698952e-03, 1.07049942e-04],
        [8.23187828e-03, 2.29046345e-02, 1.69670582e-03],
        [1.12814903e-02, 8.20302963e-03, 2.80386209e-02],
        [5.37693501e-03, 5.00917435e-04, 4.87017632e-03],
        [2.82430649e-03, 1.00611448e-02, 1.00235939e-02],
        [5.06639481e-04, 1.51945353e-02, 2.18153000e-05],
        [2.11429596e-03, 2.92265415e-03, 2.16926336e-02],
        [1.94311142e-04, 5.57792187e-03, 6.89685345e-03],
        [2.40123272e-03, 5.72645664e-03, 5.73897362e-03],
        [1.42860413e-03, 9.58025455e-03, 2.76994705e-03],
        [1.82449818e-03, 2.05922127e-03, 1.61051750e-03],
        [1.14012957e-02, 1.74522400e-04, 2.77785063e-02],
        [1.13404989e-02, 8.70680809e-03, 1.65319443e-03],
        [7.36784935e-03, 1.11556053e-03, 1.47461891e-04],
        [1.26575232e-02, 6.35755062e-03, 3.73601913e-03],
        [1.96051598e-

In [31]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

tensor = tf.random.Generator.from_seed(0)
tensor = tensor.uniform(shape = (1,224,224,3))
tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.31179297, 0.8263413 , 0.6849456 ],
         [0.0067091 , 0.78749514, 0.3906511 ],
         [0.29263055, 0.99216926, 0.95810425],
         ...,
         [0.43970728, 0.976676  , 0.8946736 ],
         [0.9747398 , 0.7011992 , 0.73613393],
         [0.4360633 , 0.7536833 , 0.01353109]],

        [[0.2823602 , 0.0927937 , 0.2424469 ],
         [0.92214036, 0.1318667 , 0.18895125],
         [0.13469017, 0.29916108, 0.22880554],
         ...,
         [0.10263181, 0.3771491 , 0.7380618 ],
         [0.6484846 , 0.69211054, 0.67284966],
         [0.43589175, 0.48166   , 0.14082742]],

        [[0.41235518, 0.45162737, 0.6804353 ],
         [0.04887676, 0.6775023 , 0.29143417],
         [0.3466624 , 0.17450547, 0.38451958],
         ...,
         [0.8667455 , 0.16113937, 0.67500424],
         [0.8560462 , 0.48929954, 0.97561824],
         [0.5725883 , 0.8036673 , 0.3923154 ]],

        ...,

        [[0.68855166, 0.3706571 , 

In [32]:
tf.squeeze(tensor)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.31179297, 0.8263413 , 0.6849456 ],
        [0.0067091 , 0.78749514, 0.3906511 ],
        [0.29263055, 0.99216926, 0.95810425],
        ...,
        [0.43970728, 0.976676  , 0.8946736 ],
        [0.9747398 , 0.7011992 , 0.73613393],
        [0.4360633 , 0.7536833 , 0.01353109]],

       [[0.2823602 , 0.0927937 , 0.2424469 ],
        [0.92214036, 0.1318667 , 0.18895125],
        [0.13469017, 0.29916108, 0.22880554],
        ...,
        [0.10263181, 0.3771491 , 0.7380618 ],
        [0.6484846 , 0.69211054, 0.67284966],
        [0.43589175, 0.48166   , 0.14082742]],

       [[0.41235518, 0.45162737, 0.6804353 ],
        [0.04887676, 0.6775023 , 0.29143417],
        [0.3466624 , 0.17450547, 0.38451958],
        ...,
        [0.8667455 , 0.16113937, 0.67500424],
        [0.8560462 , 0.48929954, 0.97561824],
        [0.5725883 , 0.8036673 , 0.3923154 ]],

       ...,

       [[0.68855166, 0.3706571 , 0.03126299],
        [0.61

In [35]:
# 9 . Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

tensor = tf.constant([1,2,3,4,5,6,7,8,9,10])
tensor.shape

TensorShape([10])

In [36]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [38]:
# 10. One-hot encode the tensor you created in 9.

tf.one_hot(tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>